import './globals.css'
import { Red_Hat_Display } from 'next/font/google'
import Nav from '@/components/Nav'

const red = Red_Hat_Display({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` ${red.className} max-w-7xl m-auto bg-[#1B1B1B] bg-none`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
