import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` ${inter.className} max-w-7xl m-auto `}>
        <h1 className='text-2xl font-bold py-5'>
          Louis Uy
        </h1>
        {children}
      </body>
    </html>
  )
}
